### ISSUE TITLE
Suggest/depend on 'curl' package

### ISSUE THREAD

**Issue by josephcmurray** [rOpenHealth/openfda#2]
Thanks for the useful openFDA wrapper. FYI openfda fails silently – returning a <code>NULL</code> data frame – when the basic README.md examples are run after <code>devtools</code>-based installation. This is due to the fact that jsonlite suggests, but does not import the <code>curl</code> package and, therefore, can't fetch the data.

Apologies if I should branch and fix, but I'm new to the GitHub game. I wasn't sure if updating DESCRIPTION was sufficient or if I'm missing something bigger. Dependency management is always a bit tricky and annoying.

Thanks! Joe

**Comment by rjpower** [comment]
Sorry for the long delay in replying.  I'll look into adding an explicit dependency on the `curl` package.  The reason for the silent failure is the rather frustrating fact that the OpenFDA API returns a 404 when a search has no results, which happens fairly often.  I don't have a lot of experience with R myself so I just caught all the errors instead (not the best idea).  I'll try to revisit this shortly.

**Comment by leeper** [comment]
Shouldn't be too hard to add some informative error messages and a couple of `stop_for_status` or `warn_for_status` statements (from **httr**). It's too bad they give a 404 because it will be hard to tease that apart from a complete failure of the API.

**Comment by rjpower** [comment]
This should be fixed with #3 .  Please re-open if you're still seeing the issue.
