### ISSUE TITLE
Failing to return exact matches

### ISSUE THREAD

**Issue by Eliford** [rOpenHealth/openfda#4]
I have noticed while implementing the code below that exact matching is not working as I expected it to.
`generic_name=fda_query("/drug/label.json")%>%
             fda_api_key(my_APIkey)%>%
             fda_search("openfda.generic_name")%>%
             fda_filter("openfda.product_type","human+prescription+drug")%>%
             fda_limit(3)%>%
             fda_exec()`
I expected the code to return a list of 3 generic names of human prescription drugs. 
But it returns a list of mix of OTC and prescription drugs. Below is the result. 
 `> generic_name
[[1]]
[1] "TITANIUM DIOXIDE, OCTINOXATE, ZINC OXIDE"

[[2]]
[1] "SULFUR, BENZOYL PEROXIDE, SALICYLIC ACID"

[[3]]
[1] "PSEUDOEPHEDRINE"`

The following query shows that "SULFUR, BENZOYL PEROXIDE, SALICYLIC ACID" is a  HUMAN OTC DRUG not a prescription drug.`https://api.fda.gov/drug/label.json?search=generic_name:%22SULFUR+BENZOYL+PEROXIDE+SALICYLIC+ACID%22`
I have decided to use the code below to get what I want.
`generic_name=fda_query("/drug/label.json")%>%
             fda_api_key(my_APIkey)%>%
             fda_search("openfda.generic_name")%>%
             fda_filter("openfda.product_type","prescription")%>%
             fda_limit(3)%>%
             fda_exec()'
result is
> generic_name
[[1]]
[1] "GLIMEPIRIDE"

[[2]]
[1] "CLARITHROMYCIN"

[[3]]
[1] "METHOCARBAMOL"

Openfda is a great package, I would like to continue using it. I am sure the issue above can be fixed.

**Comment by Eliford** [comment]
I just figured out myself that I suppose to surround values with `%22value%22`. In this case  fda_filter("openfda.product_type","%22human+prescription+drug%22")

**Comment by rjpower** [comment]
@Eliford thanks for the update.

One important note: when searching for exact matches for a phrase, you can use the `.exact` suffix for most fields to search for exactly the phrase you're querying for:

https://open.fda.gov/update/ten-things-to-know-about-adverse-events/#use-exact-to-count-for-phrases

Otherwise the API will try to search for individual words within your query, which may not be what you want.
